### PR TITLE
PARQUET-2054: fix TCP leaking when calling ParquetFileWriter.appendFile

### PR DESCRIPTION
**Pull request by vectorijk**
use try-with-resource clause to close ParquetFileReader explicitly to prevent TCP leaking issue

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by gszadovszky — APPROVED** [review]

**Comment by shangxinli** [comment]
Thanks, Kai for working on this! Can you check if there are other places having a similar issues?

**Comment by vectorijk** [comment]
Thanks, Xinli and Gabor! I will search it globally to see if any other places having this similar issue.

**Comment by gszadovszky** [comment]
@vectorijk, any updates on this? Do you plan to search similar issues under this PR or we can consider it complete?

**Comment by vectorijk** [comment]
Hi @gszadovszky , Xinli, could you help to have another look when you have time? I search globally for the similar issue (not closed `ParquetFileReader`).  It mainly happens in parquet-cli commands and ParquetFileWriter unit tests.

**Review by gszadovszky — APPROVED** [review]
Thanks a lot, @vectorijk for you efforts!

**Pull request merged**
