### PR TITLE
PARQUET-1684: dont store default protobuf values as null for proto3

### PR DESCRIPTION
**Pull request by bagipriyank**
addresses https://issues.apache.org/jira/browse/PARQUET-1684

### CODE REVIEW

**Comment by lzuwei** [comment]
Any timeline when this will be reviewed? We are also encountering NaN issues with default protobuf 3 values and we like to see if this can be fixed on parquet-protobuf library

**Comment by Fokko** [comment]
I have little knowledge about the protobuf part. Maybe @julienledem or @lukasnalezenec can shed some light on this? :)

**Comment by bagipriyank** [comment]
any updates on this?

**Comment by bagipriyank** [comment]
@julienledem @lukasnalezenec could you please have a look?

**Comment by sarathdeevi** [comment]
Any updates on this one? It seems like a valid issue and needs to be resolved.

**Comment by georgehdd** [comment]
Any updates here?

**Comment by bagipriyank** [comment]
how can i help to get some eyes on this pr?

**Comment by sarathdeevi** [comment]
Hey, wassup??

**Comment by denizkenan** [comment]
Has anyone happen to care this?

**Comment by Fokko** [comment]
The main issue here is that there are no Protobuf committers active on the project anymore. Did someone already this patch already in a production environment?

**Comment by bagipriyank** [comment]
I submitted this pr after we started using it in production :)

**Comment by sarathdeevi** [comment]
Is there a new release version for the merged PR? i still see 1.11.0 in the maven repository.

**Comment by Fokko** [comment]
Yes, there is, and you can find it in the ticket: https://issues.apache.org/jira/browse/PARQUET-1684 It is targeted at 1.12.

**Comment by dossett** [comment]
Can it be considered for 1.11.1? I see a release candidate is out.

**Comment by dossett** [comment]
cc @gszadovszky it looks like you are driving 1.11.1 (apologies if that is not the case)

**Comment by gszadovszky** [comment]
@dossett,
Strictly speaking this is not a regression in 1.11.0 so not required for 1.11.1. I am not an expert of protobuf (neither in parquet-protobuf) so let me ask the following questions:
- Do we have a workaround for this issue?
- What do we think about the potential regression this change may cause? (1.11.1 shall be 100% compatible with 1.11.0 and should not contain any regressions only bugfixes that breaks the usage of 1.11.0.)

**Comment by dossett** [comment]
Maybe of interest to the people watching this PR, I posed a question about how `oneof` fields are treated after this patch was applied.

http://mail-archives.apache.org/mod_mbox/parquet-dev/202009.mbox/browser

**Pull request merged**
