### PR TITLE
PARQUET-1198: Bump java source and target to java8

### PR DESCRIPTION
**Pull request by gszadovszky**

### CODE REVIEW

**Comment by gszadovszky** [comment]
Travis has interrupted the test after waiting 10mins for `org.apache.parquet.format.converter.TestParquetMetadataConverter`. In my environment every test runs just fine.
Any idea what the problem is? Is there a way I can build up an environment similar to the Travis one?

**Comment by zivanfi** [comment]
Hmm, could that be some unrelated transient error? I don't see any way to rerun the Travis job, maybe you could try rebasing (I just merged in another change) to retrigger Travis.

**Comment by masayuki038** [comment]
FYI:
https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by xhochy** [comment]
@zivanfi You need to `git commit --amend && git push --force` for now. In future, we should move this repo to Apache's GitBox service. With it, commiters get also access to the Travis jobs and can retrigger there (working nicely with `parquet-cpp`).

**Comment by zivanfi** [comment]
I considered logging in to Travis with my GitHub account in the hope it may show me a "rerun" button if I'm logged in. However, Travis asks for a ridicoulus amount of permissions, including _write_ access to "Repository webhooks and services" and "Commit statuses" that I did not feel comfortable with.

**Pull request closed without merging**
