### PR TITLE
PARQUET-375: Update current release version in README.md

### PR DESCRIPTION
**Pull request by lresende**
Current README.md was still pointing to release 1.7.0

### CODE REVIEW

**Comment by lresende** [comment]
@isnotinvain Could you please do a quick review on these changes

**Comment by isnotinvain** [comment]
+1, thank you!

**Comment by isnotinvain** [comment]
@lresende actually, can you rename this PR to begin with a jira, eg: https://github.com/apache/parquet-mr/pull/266

Thanks!

**Comment by lresende** [comment]
@isnotinvain Done, I have created a JIRA and update the PR info.

**Comment by isnotinvain** [comment]
@lresende sorry, the merge script can't currently handle the brackets around the jira, can you rename w/o the brackets? I've sent https://github.com/apache/parquet-mr/pull/271, if that gets merged first, then I can merge this one as-is. Sorry for the confusion!

**Comment by lresende** [comment]
@isnotinvain Titles fixed

**Pull request closed without merging**
