### PR TITLE
PARQUET-1847: Filter out github notification from dev mail list

### PR DESCRIPTION
**Pull request by chenjunjiedada**

### CODE REVIEW

**Comment by chenjunjiedada** [comment]
@wesm, Could you please help to take a look?

**Comment by wesm** [comment]
github@ doesn't exist for parquet.a.o so either this traffic should be directed to another mailing list, or a new one should be created. 

Pausing for a second, we should probably confirm on dev@ where people want these e-mails to go

**Comment by chenjunjiedada** [comment]
Got it. Maybe we need a vote to choose solutions.

**Comment by chenjunjiedada** [comment]
@wesm , I guess you are familiar with infra setup. Would you please help to list the options and start a vote thread for this?

**Pull request closed without merging**
