### PR TITLE
Merge master to bloom filter branch

### PR DESCRIPTION
**Pull request by chenjunjiedada**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by chenjunjiedada** [comment]
One of CI-check failed, looks like some infra related. Close and reopen to trigger again.

**Comment by chenjunjiedada** [comment]
Hi @gszadovszky,

I just re-submit this, in order to align the bloom filter implementation to format, we need some minor updates on the bloom-filter branch. IIRC, we need to merge the parquet master branch back to the bloom-filter branch. Could you please help to merge this bloom-filter branch? I can open a rebase PR if we need a rebase instead.

**Comment by gszadovszky** [comment]
Hi @chenjunjiedada, 
I think, it is more clear to rebase the bloom filter branch.
Just checked and the rebase to master is not clean so please do it on your private branch and solve the conflicts. Then, I'll force-push your branch to origin/bloom-filter. (I don't know if a PR would make sense. I don't think Github supports force push.)

**Comment by chenjunjiedada** [comment]
Thanks @gszadovszky 

I found a merging strategy [here ](https://lists.apache.org/thread.html/b923f9608e9d6d59f1040bb196b4aca176d1c06f838dda0b28020ebd@%3Cdev.parquet.apache.org%3E)

It recommends the following way:

- The feature branch is handled similar to the master branch:
developers open pull requests, committers review, approve and merge
them by squashing each pull request into a single commit on the
feature branch.
- The feature branch developers may occasionally merge the master
branch into the feature branch. (This needs some extra manual work
from the committer, since merges are disabled on the github UI on
purpose.)
- When the feature branch is ready, its developers open a pull request
for merging it into master. Committers should merge such a pull
request by squashing it but mentioning the feature branch name and
keeping the list of commits in the commit message at the same time.
This allows interested parties to trace back the history of affected
code lines by consulting the feature branch history and/or pull
request reviews.

What do you think about doing in this way?

**Comment by gszadovszky** [comment]
I think, it is up to the feature branch developers whether they want to rebase the branch from time to time or merge the master into it. If you would like to do the latter, I'm also happy to do that.

**Comment by chenjunjiedada** [comment]
I 'd follow the merging way. Thanks.

**Pull request merged**
