### PR TITLE
PARQUET-1722: Update scala-maven-plugin

### PR DESCRIPTION
**Pull request by garawalid**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by Fokko** [comment]
@garawalid Can you rebase against the latest master?

**Comment by garawalid** [comment]
Thank you @Fokko. 
I find it weird that there is a timout in the Travis CI build. Do you have any thoughts ?

**Comment by garawalid** [comment]
The problem comes from **parquet-hadoop-bundle**. 
It turns out that the `maven-shade-plugin` gets stuck in an infinite loop while building the dependency graph of `org.apache.parquet:parquet-scala_2.12:jar:1.12.0-SNAPSHOT`.

```log
DEBUG] building maven31 dependency graph for org.apache.parquet:parquet-scala_2.12:jar:1.12.0-SNAPSHOT with Maven31DependencyGraphBuilder
[DEBUG] aether.artifactDescriptor.threads = 5
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=12919, ConflictMarker.markTime=5213, ConflictMarker.nodeCount=29, ConflictIdSorter.graphTime=10143, ConflictIdSorter.topsortTime=17271, ConflictIdSorter.conflictIdCount=19, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=81683, ConflictResolver.conflictItemCount=28, DefaultDependencyCollector.collectTime=979457, DefaultDependencyCollector.transformTime=133229}
[DEBUG] org.apache.parquet:parquet-scala_2.12:jar:1.12.0-SNAPSHOT
[DEBUG]    org.apache.parquet:parquet-column:jar:1.12.0-SNAPSHOT:compile
[DEBUG]       org.apache.parquet:parquet-common:jar:1.12.0-SNAPSHOT:compile
[DEBUG]          org.apache.parquet:parquet-format-structures:jar:1.12.0-SNAPSHOT:compile
[DEBUG]             javax.annotation:javax.annotation-api:jar:1.3.2:compile
[DEBUG]          org.apache.yetus:audience-annotations:jar:0.11.0:compile
[DEBUG]       org.apache.parquet:parquet-encoding:jar:1.12.0-SNAPSHOT:compile
[DEBUG]       it.unimi.dsi:fastutil:jar:8.2.3:compile
[DEBUG]    org.scala-lang:scala-library:jar:2.12.8:compile
[DEBUG]    org.scalatest:scalatest_2.12:jar:3.0.1:test
[DEBUG]       org.scalactic:scalactic_2.12:jar:3.0.1:test
[DEBUG]       org.scala-lang:scala-reflect:jar:2.12.0:test
[DEBUG]       org.scala-lang.modules:scala-xml_2.12:jar:1.0.5:test
[DEBUG]       org.scala-lang.modules:scala-parser-combinators_2.12:jar:1.0.4:test
[DEBUG]    org.slf4j:slf4j-simple:jar:1.7.22:test
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.22:compile
[DEBUG]    junit:junit:jar:4.12:test
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.3:test
[DEBUG]    org.easymock:easymock:jar:3.4:test
[DEBUG]       org.objenesis:objenesis:jar:2.2:test
```
I tried even the older version of `scala-maven-plugin` 3.0.2 and it didn't work.

**Comment by garawalid** [comment]
I'll close the PR. Thank you @Fokko for your review.

**Pull request closed without merging**
