### PR TITLE
PARQUET-404: Replace git@github.com.apache for HTTPS URL on dev/README.md to avoid permission issues

### PR DESCRIPTION
**Pull request by spena**
…lic key on committer github account is needed

@julienledem @rdblue @liancheng Could you help me review this trivial patch for dev/README.md?

### CODE REVIEW

**Comment by rdblue** [comment]
Is that true? I thought that you could use the HTTPS URL without problems if you were doing read-only operations.

**Comment by spena** [comment]
git@github.com:apache/parquet-mr.git did not work for me when running the script because I did not have the public key in my github account, and it was only fetching code when it failed. Should we replace git@ to the https url instead?

**Comment by rdblue** [comment]
Yeah, we should try it with the HTTPS URL. It isn't surprising that the SSH URL fails because you can't log in at all. The HTTPS one should work for read-only and I think it is better to recommend that one.

**Comment by spena** [comment]
@rdblue I did the change to HTTPS. The permission issue does not happen even if I don't have my public key on my github.

**Comment by rdblue** [comment]
+1

Thanks Sergio!

**Comment by liancheng** [comment]
+1

**Pull request closed without merging**
