### PR TITLE
PARQUET-2037: Write INT96 with parquet-avro

### PR DESCRIPTION
**Pull request by gszadovszky**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by shangxinli** [comment]
In the ticket, you mentioned there are two ways to solve this issue. I see you implemented it using the 2nd way. I wonder what is the reason behind it?  I am not in favor of one over the other, just want to know what are the pros and cons for each.

**Comment by gszadovszky** [comment]
@shangxinli,
The other option was about using the `doc` field of the avro schema field. It would be a misuse of it as anyone can set anything to that field. It is more about documenting the related field for humans instead of taking decisions based on it in the code. On the Parquet sync that was my only idea to resolve this issue and even I did not like it.
I think the 2nd option (covered by this PR) is much better but only realized its possibility after the Parquet sync meeting so we could not discuss it personally.

**Comment by shangxinli** [comment]
Yeah, agree. Just one thing that sometimes it might not be straightforward for the user to know the exact path to manually set in the configuration for some deeply nested schema.  I remember last time when I worked on Avro schema, there are 20+ layers nested in the field and there are 'Type' in the middle with 'name' in it. That is not very human being readable and easy to make mistake. But I have less experience working on Schema, I am not certain this is a real issue.

**Comment by gszadovszky** [comment]
@shangxinli, I agree this is not a perfect solution but I could not come up with any better one. Meanwhile, this feature will not be used widely since INT96 is deprecated. Maybe, it is even better that this feature is not always easy to use :)

**Pull request merged**
