### PR TITLE
PARQUET-2230: [CLI] Deprecate commands replaced by rewrite

### PR DESCRIPTION
**Pull request by wgtmac**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. 
  - https://issues.apache.org/jira/browse/PARQUET-2230

### Tests

- [x] My PR does not need testing.

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - Remove all deprecated commands supported by parquet-cli from README.md.

### CODE REVIEW

**Comment by wgtmac** [comment]
Deprecate some commands. Please take a look, thanks!
@gszadovszky @ggershinsky @shangxinli

**Review by gszadovszky — CHANGES_REQUESTED** [review]
@wgtmac, the interface of parquet-cli is not the code but the commands. We are excluding parquet-cli from compatibility checks anyway, so you can modify the code as you wish (no deprecation is required). But I think we should version the contract of the cli similarly so not removing a command but highlight somehow that the other tool should be used instead. What do you think?

**Comment by wgtmac** [comment]
> @wgtmac, the interface of parquet-cli is not the code but the commands. We are excluding parquet-cli from compatibility checks anyway, so you can modify the code as you wish (no deprecation is required). But I think we should version the contract of the cli similarly so not removing a command but highlight somehow that the other tool should be used instead. What do you think?

That makes sense.

I have added the deprecated message to the command description. WDYT? @gszadovszky

**Review by gszadovszky — APPROVED** [review]

**Comment by gszadovszky** [comment]
Thanks a lot, @wgtmac. It looks good to me.

**Comment by gszadovszky** [comment]
(Congrats for the committership! From now on I won't push your PRs. :wink: )

**Comment by wgtmac** [comment]
> (Congrats for the committership! From now on I won't push your PRs. 😉 )

Thank you for your help all the time! @gszadovszky

**Pull request merged**
