### PR TITLE
PARQUET-246: fix incomplete state reset in DeltaByteArrayWriter.reset()

### PR DESCRIPTION
**Pull request by kostya-sh**
...thod

### CODE REVIEW

**Comment by isnotinvain** [comment]
+1

**Comment by isnotinvain** [comment]
@kostya-sh can you merge master into this branch, then take a look at: https://github.com/kostya-sh/incubator-parquet-mr/pull/1

**Comment by kostya-sh** [comment]
@isnotinvain Done.

**Comment by isnotinvain** [comment]
Thank you!

**Pull request closed without merging**
