### PR TITLE
PARQUET-2355: Remove `parquet-thrift`

### PR DESCRIPTION
**Pull request by Fokko**
Parquet Thrift relies on Elephantbird:

https://github.com/twitter/elephant-bird

And the current version is still on Thrift 0.7.0, and this doesn't work with 0.19.0 that we're trying to upgrade to. Updating is non-trivial since a lot of the code that was used for testing has been made private: https://github.com/apache/parquet-mr/pull/1156

I would suggest removing this from the repository since it looks like no one is using it anymore:

`apache-thrift` does not seem to be used anymore (usages of 0 since 1.12.2): 

image

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-2355
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by mystic-lama** [comment]
Do we want to make it deprecated now and remove in a major release?

**Comment by Fokko** [comment]
@mystic-lama That's a possibility. I've sent out an email on the dev list with some more context: https://lists.apache.org/thread/bk74c7bk1wr63y5rw6tjwkxvdjjfb8kl The downside of keeping this is that we have to release with an old version of Thrift, which has challenges (you have to compile it locally for OSX). I've created a PR here to see [what's](https://github.com/apache/parquet-mr/pull/1138/) changed. Also, bumping elephantbird is not a possibility, see #1156

**Comment by mystic-lama** [comment]
@Fokko I am following the discussion ☺️ 

I am all in favor of dropping it, just thinking from User perspective. Once they know the change is coming, they can prepare for it.

**Comment by Fokko** [comment]
@mystic-lama That would be the cleanest way, but as I pointed out on the maillist, it has been almost 3 years since the latest PR has been raised against the `parquet-thrift` module. Those using it can still use the already-released versions.

**Pull request closed without merging**
