### PR TITLE
PARQUET-1971: Flaky test in github action

### PR DESCRIPTION
**Pull request by gszadovszky**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by wangyum — COMMENTED** [review]
It seems this flaky test caused by latest JDK 1.8. It works if we change it to `8.0.252`:
```diff
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 15bd07c92f..f620ac1a61 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,7 +9,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        java: [ '1.8', '11' ]
+        java: [ '8.0.252', '11' ]
         codes: [ 'uncompressed,brotli', 'gzip,snappy' ]
     name: Build Parquet with JDK ${{ matrix.java }} and ${{ matrix.codes }}
```


travis JDK 1.8 version:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

Github action JDK 1.8 version:
```
2021-02-02T15:56:28.8392470Z env:
2021-02-02T15:56:28.8392877Z   JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-02-02T15:56:28.8393377Z   JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
2021-02-02T15:56:28.8393883Z   JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
```

**Comment by wangyum** [comment]
I have tested it four times:
image

**Comment by gszadovszky** [comment]
Thanks, @wangyum for checking this. Also, I am not sure about the related test anyway. That percentage of validating the limit was already changed 3 times.
I am fine with both ways. If you think the upgrading of the jdk8 version is a better solution feel free to create another PR for this jira and I am happy to review/push it.

**Comment by gszadovszky** [comment]
Closing this in favor of #864

**Comment by gszadovszky** [comment]
Seems that #864 did not solve the problem. Back to this solution.

**Review by wangyum — APPROVED** [review]

**Pull request merged**
