### PR TITLE
PARQUET-1448: Review of ParquetFileReader (rebased)

### PR DESCRIPTION
**Pull request by dossett**
This is rebased version of @belugabehr's original PR for this JIRA (https://github.com/apache/parquet-mr/pull/586)

### CODE REVIEW

**Review by gszadovszky — APPROVED** [review]
Thanks a lot, @dossett for picking this up!

**Comment by gszadovszky** [comment]
Sorry, but another approved PR has got in and its conflicting. @dossett, could you please do a rebase on this one so I can push it?

**Comment by dossett** [comment]
No problem, @gszadovszky.  done.

**Review by Fokko — APPROVED** [review]

**Comment by belugabehr** [comment]
Super cool.  Thanks for getting this across the finish line!

**Comment by belugabehr** [comment]
Super cool.  Thanks for getting this across the finish line!

**Pull request merged**
