### PR TITLE
PARQUET-1842: Update jackson-databind version

### PR DESCRIPTION
**Pull request by patrickofriel-wk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet-1842](https://issues.apache.org/jira/browse/PARQUET-1842)
  - https://issues.apache.org/jira/browse/PARQUET-1842.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: patch update to jackson-databind, should be covered by existing tests

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - No new functionality

### CODE REVIEW

**Comment by patrickofriel-wk** [comment]
Anything else you'd like me to do before merging this @Fokko ?

**Comment by Fokko** [comment]
@patrickofriel-wk No nothing from your side. It is just common courtesy to wait a bit, so other committers/PMC can response, before merging. Thanks for your contribution @patrickofriel-wk

**Comment by patrickofriel-wk** [comment]
Makes sense, thanks for the quick review @Fokko !

**Comment by Fokko** [comment]
My pleasure @patrickofriel-wk

**Pull request merged**
