### PR TITLE
Merge master branch into bloom filter branch

### PR DESCRIPTION
**Pull request by chenjunjiedada**
This PR merge the master branch into the bloom filter branch.

### CODE REVIEW

**Comment by chenjunjiedada** [comment]
@Fokko, I found we have many trailing spaces in source code especially in license comment (my intellij IDE always strip them when saving changes and thus got the diffs, parquet contributors may not use intellij?). Do we have any plugin that can ensure no trailing space in source code? I know Iceberg has one through style check.

**Comment by gszadovszky** [comment]
I think, it would be more readable to initiate the PR from a merge commit instead of squashing all the changes. Then, I'll be able to push the merge commit to the feature branch. In addition, I think it is not the latest master.

**Comment by chenjunjiedada** [comment]
@gszadovszky, I see you have a commit for checking API backward compatibility. There are some APIs changes between 1.11.0 and your commit point.  see the following:
`
WARNING: Incompatibility detected: Requires semantic version level MAJOR: JApiField [changeStatus=MODIFIED, jApiClass=JApiClass [fullyQualifiedName=org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter, changeStatus=MODIFIED, compatibilityChanges=[]], oldFieldOptional=org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter.binaryDictionaryContent:Lshaded/parquet/it/unimi/dsi/fastutil/objects/Object2IntMap;, newFieldOptional=org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter.binaryDictionaryContent:Lit/unimi/dsi/fastutil/objects/Object2IntMap;, annotations=[], accessModifier=japicmp.model.JApiModifier@6c54f562, staticModifier=japicmp.model.JApiModifier@416fb444, finalModifier=japicmp.model.JApiModifier@7adfff81, transientModifier=japicmp.model.JApiModifier@1580d7d3, syntheticModifier=japicmp.model.JApiModifier@3c7f83b, syntheticAttribute=japicmp.model.JApiAttribute@102d2988, compatibilityChanges=[FIELD_TYPE_CHANGED], type=japicmp.model.JApiType@4873e2c4]
Jan 07, 2020 11:37:28 PM japicmp.output.incompatible.IncompatibleErrorOutput warn
WARNING: Incompatibility detected: Requires semantic version level MAJOR: JApiMethod [oldMethod=org.apache.parquet.filter2.recordlevel.FilteringRecordMaterializer.getIndexFieldPathList(org.apache.parquet.io.PrimitiveColumnIO), newMethod=n.a., returnType=JApiReturnType [oldReturnTypeOptional=java.util.List, newReturnTypeOptional=value absent, changeStatus=REMOVED], getCompatibilityChanges()=[METHOD_REMOVED]]
Jan 07, 2020 11:37:28 PM japicmp.output.incompatible.IncompatibleErrorOutput warn
WARNING: Incompatibility detected: Requires semantic version level MAJOR: JApiMethod [oldMethod=org.apache.parquet.filter2.recordlevel.FilteringRecordMaterializer.intArrayToList(int[]), newMethod=n.a., returnType=JApiReturnType [oldReturnTypeOptional=java.util.List, newReturnTypeOptional=value absent, changeStatus=REMOVED], getCompatibilityChanges()=[METHOD_REMOVED]]
`

So this PR should not pass travis check.  Should we fix the API changes?

**Comment by gszadovszky** [comment]
@chenjunjiedada, Yes, please fix the compatibility issues.
The configuration of japicmp should catch only the modifications that are incompatible with the 1.11.0 release. If you have issues fixing the findings or you think some findings are false then please, send me the report file so I can check them out.

**Comment by chenjunjiedada** [comment]
@gszadovszky, Since these API changes that are not compatible are not related to this PR, so it would be better to create a separated JIRA and PR to fix them. What do you think?

**Comment by gszadovszky** [comment]
@chenjunjiedada, I agree. However, I would feel better merging a PR if it passes the tests.
If it is not too much work, would you do your changes based on this merge so you can see if they passes the compatibility checks, and then cherry-pick back to the current feature branch and initiate a PR? After that PR gets in, we'll restarts the failing tests here and we shall see them pass.

**Comment by chenjunjiedada** [comment]
@gszadovszky, No problem, let me do this.

**Comment by chenjunjiedada** [comment]
@gszadovszky, Since the master branch build is broken, I created PARQUET-1741 to track this.

**Comment by gszadovszky** [comment]
Sorry, @chenjunjiedada, I've missed that master is broken. I've thought, the changes in the bloom-filter branch causes the failure.
Thanks a lot for working on the fix.

**Comment by chenjunjiedada** [comment]
@gszadovszky, I tried to merge latest master but still lag behind one commit. Can we merge this at first?

**Comment by chenjunjiedada** [comment]
Three builds passed, the one failed due to fail to download jar. @Fokko Could you please help to trigger CI again?

**Comment by Fokko** [comment]
Sure, retriggered the build. Kind of flakey lately :'(

**Pull request merged**
