### PR TITLE
MINOR: try to fix github workflow timeout

### PR DESCRIPTION
**Pull request by wgtmac**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references
  them in the PR title. For example, "PARQUET-1234: My Parquet PR"
    - https://issues.apache.org/jira/browse/PARQUET-XXX
    - In case you are adding a dependency, check if the license complies with
      the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines
  from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    1. Subject is limited to 50 characters (not including Jira issue reference)
    1. Subject does not end with a period
    1. Subject uses the imperative mood ("add", not "adding")
    1. Body wraps at 72 characters
    1. Body explains "what" and "why", not "how"

### Style
- [ ] My contribution adheres to the code style guidelines and Spotless passes.
    - To apply the necessary changes, run `mvn spotless:apply -Pvector-plugins`

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Thanks for fixing this @wgtmac

**Comment by wgtmac** [comment]
> Thanks for fixing this @wgtmac

Thanks for the quick review! @Fokko 

I'm not sure if this works. Just trying to figure it out.

**Comment by wgtmac** [comment]
It seems that all failed tests are stuck after the logs below:
```
[INFO] Running org.apache.parquet.hadoop.rewrite.ParquetRewriterTest
2024-02-07 05:46:14 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test2346352174745648346/test.parquet
2024-02-07 05:50:18 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test4379236561694789134/test.parquet
2024-02-07 05:54:22 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test766034279661702122/test.parquet
2024-02-07 05:58:24 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test2729433322483965446/test.parquet
2024-02-07 06:02:26 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test7414379030048432860/test.parquet
2024-02-07 06:06:28 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test7003467635545421733/test.parquet
2024-02-07 06:10:31 ERROR ParquetRewriter - Input files have different schemas, expect: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
  optional group Links {
    repeated binary Backward;
    repeated binary Forward;
  }
}
, input: message schema {
  optional int64 DocId;
  required binary Name;
  optional binary Gender;
}
, current file: file:/tmp/test4733487932943484705/test.parquet
```

**Comment by wgtmac** [comment]
Ah, it works. Do you want to take a look again? @Fokko

**Comment by Fokko** [comment]
Nice one @wgtmac Thanks for fixing this 🙌

**Pull request merged**
