### PR TITLE
PARQUET-1942: Bump Apache Arrow to 2.0.0

### PR DESCRIPTION
**Pull request by Fokko**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-1942
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by gszadovszky — CHANGES_REQUESTED** [review]
It does not seem to be that easy. Please check Travis failures.

**Comment by gszadovszky** [comment]
@Fokko, It seems it still needs some additional work. 

@martin-g, do you have an idea how it is possible that Travis did not fail because of this issue?

**Comment by martin-g** [comment]
@gszadovszky Checking ...

**Comment by martin-g** [comment]
@gszadovszky Fixed with https://github.com/apache/parquet-mr/pull/890

**Comment by martin-g** [comment]
@Fokko Could you please rebase from latest master so we can see that TravisCI fails too ?

**Comment by martin-g** [comment]
@psilos You could help by creating a new PR with Arrow 13 and by making sure that the CI pass!

TravisCI is no more in use for testing on Linux ARM64! If the project is interested I could create a PR that uses the new ASF managed self-hosted runners at Github Actions!

**Comment by wgtmac** [comment]
> What's the status of this PR? Can we upgrade arrow as it's on a very old dependency and latest version has moved to 13.0.0 now ?
> 
> Let me know if I can help in any way ? :)
> 
> CC @Fokko @martin-g @gszadovszky

Do you want to create a PR for this? BTW, how do you use parquet-arrow in your case? @psilos

**Comment by Fokko** [comment]
Closing in favor of https://github.com/apache/parquet-mr/pull/1193

**Pull request closed without merging**
