### PR TITLE
PARQUET-2050: Expose repetition & definition level from ColumnIO

### PR DESCRIPTION
**Pull request by sunchao**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by sunchao** [comment]
For rationale, please check the JIRA https://issues.apache.org/jira/browse/PARQUET-2050. Not sure where should I put those in the PR description.

**Comment by sunchao** [comment]
@shangxinli @ggershinsky @gszadovszky could you review this? Thanks!

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by shangxinli** [comment]
@gszadovszky Is there any concern from you?

**Review by gszadovszky — CHANGES_REQUESTED** [review]
I am fine having these methods public if it is required for our users. Meanwhile, since it is public, it would be great having the proper javadoc comments for them.

**Comment by sunchao** [comment]
Thanks for the review @gszadovszky . Added.

**Review by gszadovszky — APPROVED** [review]

**Comment by shangxinli** [comment]
LGTM. After fixing the checks failure, we can merge.

**Comment by sunchao** [comment]
Thanks @shangxinli and @gszadovszky . Do you know how to see the details for the check failures? I opened the link and it just shows "This check failed".

**Comment by sunchao** [comment]
Let me trigger the CI again to find out why.

**Comment by gszadovszky** [comment]
I don't know why we had such failures but they were not only for this PR. As they are passing now I'm merging this PR.

**Pull request merged**
