### PR TITLE
PARQUET-269: Restore scrooge-maven-plugin to version 3.17.0

### PR DESCRIPTION
**Pull request by isnotinvain**
Scrooge has re-published scrooge-maven-plugin 3.17.0, so we should be able to use it again.
Lets see if travis is able to pick up the changes.

### CODE REVIEW

**Comment by isnotinvain** [comment]
tests running here https://travis-ci.org/isnotinvain/incubator-parquet-mr/builds/60754233

**Comment by isnotinvain** [comment]
Tests passed in my travis queue, and 1 of the test profiles in the apache queue failed due to what looks like a transient error downloading jars from maven central.

**Comment by isnotinvain** [comment]
@tsdeng @rdblue lets get this merged ASAP

**Comment by rdblue** [comment]
+1

Thanks for fixing this!

**Pull request closed without merging**
