### PR TITLE
PARQUET-685 - Deprecated ParquetInputSplit constructor passes paramet…

### PR DESCRIPTION
**Pull request by gszadovszky**
The problem was not discovered because the test was bugous. Updated both sides.

### CODE REVIEW

**Comment by piyushnarang** [comment]
👍

**Comment by julienledem** [comment]
+1

**Comment by julienledem** [comment]
@rdblue opinion on this? Is this used by Hive?

**Comment by rdblue** [comment]
+1

I don't think this is used by Hive, and even if it were it's still a bug that should be fixed.

**Pull request closed without merging**
