### PR TITLE
PARQUET-329: Restore ThriftReadSupport#THRIFT_COLUMN_FILTER_KEY

### PR DESCRIPTION
**Pull request by SinghAsDev**
ThriftReadSupport#THRIFT_COLUMN_FILTER_KEY was removed (incompatible change)

### CODE REVIEW

**Comment by SinghAsDev** [comment]
@rdblue could you take a look at this?

**Comment by rdblue** [comment]
I think this should also fix the semver exclusions.

**Comment by SinghAsDev** [comment]
@rdblue looks like we missed out on merging [this](https://github.com/SinghAsDev/parquet-mr/commit/1e44a7049576e4a4a5629d4ae33d97de72f9c87b#diff-600376dffeb79835ede4a0b285078036L222) change. Can we do it now or do I need to create a separate JIRA for it?

**Comment by rdblue** [comment]
This was merged, it just hasn't shown up in github yet because sync is down. I've notified github and they are working on it.

**Comment by SinghAsDev** [comment]
Thanks @rdblue !

**Pull request closed without merging**
