### PR TITLE
PARQUET-2096: Upgrade Thrift to 0.15.0

### PR DESCRIPTION
**Pull request by vinooganesh**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-2096
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: library upgrade

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by vinooganesh** [comment]
@rdblue This is a baby commit - but could you approve running tests on it?

**Comment by vinooganesh** [comment]
cc @gszadovszky @sunchao from https://github.com/apache/parquet-mr/pull/927. @sunchao - apologies for the quick upgrade after yours, I saw was building parquet from source and saw that brew out of the box is on thrift 0.15.0 now and figured I'd quickly upgrade the dep assuming there are no problems.

**Review by gszadovszky — APPROVED** [review]

**Review by sunchao — APPROVED** [review]
np @vinooganesh . +1 on this too

**Comment by vinooganesh** [comment]
@gszadovszky - thanks for the approval! Please let me know if there is anything else I need to do before we merge.

**Comment by dongjoon-hyun** [comment]
Thank you, @vinooganesh and all. I also hit this issue. :)

**Comment by gszadovszky** [comment]
@vinooganesh, everything is fine. Only that I usually wait for additional 24 hours before merging so others have a chance to complain.

**Pull request merged**
