### PR TITLE
PARQUET-2161: Fix row index generation in combination with range filtering

### PR DESCRIPTION
**Pull request by ala**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-2161
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  - Extends `TestParquetReader` suite. 

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by ala** [comment]
cc @shangxinli This is a small follow-up bug fix for https://github.com/apache/parquet-mr/pull/945

**Comment by ala** [comment]
cc @ggershinsky

**Comment by ggershinsky** [comment]
Yep, I remember reviewing that PR. @prakharjain09 , can you also have a look at this fix?

**Comment by chenjunjiedada** [comment]
This looks correct to me. The logic also exists in the iceberg row position reader. See: https://github.com/apache/iceberg/pull/1254#discussion_r461893642.

**Review by chenjunjiedada — APPROVED** [review]

**Comment by ggershinsky** [comment]
Thanks @chenjunjiedada . 
@ala , please handle the message comment, and I'll merge this PR.

**Comment by ala** [comment]
@ggershinsky Thanks for the review. I tweaked the error assertion message to better match the rest of the codebase.

**Review by prakharjain09 — APPROVED** [review]
Thanks a lot for fixing this issue @ala . Changes looks good to me.

**Comment by ggershinsky** [comment]
Thanks @ala

**Comment by ala** [comment]
@ggershinsky Do you know when the next release that will include the fix might happen? We are looking to unblock https://issues.apache.org/jira/browse/SPARK-39634 in Apache Spark.

**Comment by ggershinsky** [comment]
cc @shangxinli

**Comment by ala** [comment]
@ggershinsky @shangxinli Hi! I just wanted to ask if 1.12.4 release might be happening soon (it seems in the previous years there usually was a release around September-October time)? We could really use the fix in Spark. Also: do I need to cherry-pick this fix, or would the next release be cut from `master`?

**Comment by shangxinli** [comment]
@ala Thanks for pinging me! At this moment, I don't have ETA yet.

**Pull request merged**
