### PR TITLE
PARQUET-1895: Update jackson-databind

### PR DESCRIPTION
**Pull request by gszadovszky**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-1895
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Dependency upgrade; no additional unit tests are required.

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by grumpyjames** [comment]
I know this PR probably doesn't meet the standards of this project, but it would be _excellent_ if it were merged anyway. The version of jackson that ends up being shaded by the project has numerous serious security vulnerabilities as detected by the OWASP dependency check tool: https://owasp.org/www-project-dependency-check/

It may be that the usage of jackson by the parquet project is not vulnerable to the 23 (!) different vulnerabilities I've got listed locally, but that's potentially very hard for someone not familiar to the project to audit, and I would hope that the travis check is sufficient to show that the upgrade is at least compile safe.

Let me know if there's anything I can do to help this get merged!

--James.

**Comment by gszadovszky** [comment]
@grumpyjames, I really hope it meets the standards :smiley:. I completely forgot about it. Thanks for the heads up.
Based on the apache policy we need an approval of a committer (even if the author is one of them).
@shangxinli, could you have a quick look on this one?

**Comment by grumpyjames** [comment]
> @grumpyjames, I really hope it meets the standards

I hope so too!

I should clarify here that I have no idea if it does or not - it looks like there's a template for PR's that's been left untouched - there are some checkboxes/questions that could be answered? But possibly this change is small enough for that to not matter! Or maybe that template is really old and no-one actually reads it! I don't know! Hopefully someone who does can have a look :-)

**Comment by gszadovszky** [comment]
Oh, I see. I am not a big fun of this template let me correct it.

**Comment by shangxinli** [comment]
LGTM

**Review by shangxinli — APPROVED** [review]

**Comment by toomyem** [comment]
When can we expect to see new version available in Maven Repository?

**Comment by gszadovszky** [comment]
This will be part of the new 1.12.0 release. I cannot say an exact ETA for it. I hope we can release it this year.

**Comment by toomyem** [comment]
Maybe some small release 1.11.2 with this fix would be possible sooner?

**Comment by gszadovszky** [comment]
I would suggest writing to the dev list of the parquet community about this topic.

**Pull request merged**
