### PR TITLE
PARQUET-726: Increase max difference of testMemoryManagerUpperLimit to 10%

### PR DESCRIPTION
**Pull request by nielsbasjes**

### CODE REVIEW

**Comment by nielsbasjes** [comment]
For this change I simply chose to not change the way the test was already done and simply add a little extra info if it fails. I can remove the extra info if you want.

**Comment by nielsbasjes** [comment]
I tried the method you mentioned and it doesn't improve the readability of the error message:
`Failed tests:   testMemoryManagerUpperLimit(org.apache.parquet.hadoop.TestMemoryManager): Pool size should be within 5.0% of the expected value expected:<4.53745044E8> but was:<4.79644871E8>
`

**Comment by julienledem** [comment]
better error messages is great. 
Hopefully this will fix the test flakiness.

**Comment by julienledem** [comment]
+1

**Pull request closed without merging**
