### PR TITLE
PARQUET-415: Fix ByteBuffer Binary serialization.

### PR DESCRIPTION
**Pull request by rdblue**
This also adds a test to validate that serialization works for all
Binary objects that are already test cases.

### CODE REVIEW

**Comment by proflin** [comment]
+1, LGTM. Good to have testSerializable() for unit tests!

So, @rdblue , should we have more committers review on this, or can we get this committed? Cheers.

**Comment by rdblue** [comment]
Thanks for reviewing, @proflin! We will need a committer to have a look as well, but it really helps to have more than one person review. Like we said in the sync-up today, we love it when non-committers help out with reviews because it makes everything go faster.

**Comment by proflin** [comment]
Sure. I'm familiar with the parquet-format/parquet-mr code base, and I would love to review more PRs. Things are going fast these days :)

BTW congratulations on your new journey at Netflix :-)

**Comment by julienledem** [comment]
+1
Thanks for the review @proflin

**Comment by jinxing64** [comment]
@rdblue 
Thanks for fixing this problem, may I ask a question?
1. What parquet version includes this change? is it 1.9.0?
2. Without this change, what exception will be thrown? is it below?
```
Caused by: java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
        at java.nio.ByteBuffer.get(ByteBuffer.java:715)
        at org.apache.parquet.io.api.Binary$ByteBufferBackedBinary.getBytes(Binary.java:405)
        at org.apache.parquet.io.api.Binary$ByteBufferBackedBinary.getBytesUnsafe(Binary.java:414)
        at org.apache.parquet.io.api.Binary$ByteBufferBackedBinary.writeObject(Binary.java:484)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
......
```

**Comment by rdblue** [comment]
@jinxing64, this is fixed in 1.9.0. It could result in the trace you pasted, I think. I'm not sure if that's actually happening though.

**Comment by jinxing64** [comment]
@rdblue 
Thanks a lot !

**Pull request closed without merging**
