### PR TITLE
PARQUET-2051: AvroWriteSupport Doesn't Pass Configuration to AvroSchemaConverter During Init

### PR DESCRIPTION
**Pull request by hailuand**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/projects/PARQUET/issues/PARQUET-2051) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
     - TestAvroWriteSupport.java

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by hailuand** [comment]
See the description in [PARQUET-2051](https://issues.apache.org/jira/projects/PARQUET/issues/PARQUET-2051) for the full driver behind the change.

In short, using the new ThreeLevelListWriter does not seem to work through the AvroParquetInputFormat as the Configuration that held the property was not passed through from AvroWriteSupport to the AvroSchemaConverter during init.

**Review by gszadovszky — APPROVED** [review]
Thanks a lot for fixing this.

**Comment by gszadovszky** [comment]
@hailuand, why have you closed this?

**Comment by hailuand** [comment]
@gszadovszky Hi Gabor, I will be re-opening this soon. I need to complete some procedures/certifications with my employer first.

**Pull request closed without merging**
