### PR TITLE
PARQUET-2025: Update Snappy version to 1.1.8.3

### PR DESCRIPTION
**Pull request by williamhyun**
This PR aims to update Snappy to 1.1.8.3 to support Mac m1.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This is a dependency update. All existing tests should pass.

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by chenjunjiedada — APPROVED** [review]

**Comment by cyraid** [comment]
May I ask why there are so many open pull requests from years ago? Is this repository dead?

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
cc @Fokko

**Review by gszadovszky — APPROVED** [review]
Thanks, @williamhyun for taking care of this. However, I am not sure if it worth the effort to do minor/patch level upgrades of our dependencies far from a release. I think, it is better to do such upgrades to the latest available releases just before a release. (I am not against this just mentioning.)

@cyraid, if the repo would be dead we would not start and accept new PRs to it. I guess the old open PRs you are talking about are more or less abandoned because no one had the time to review/close them. Feel free to contribute and comment to these PRs if you think they worth a re-check or we should close them. Also, this topic is not related to this particular PR so please do not comment here. Feel free to open a discussion about this topic on the dev mailing list.

**Review by Fokko — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun and all.

This will unblock Apache Parquet snappy development in Apple Silicon environment!

**Pull request merged**
