### PR TITLE
PARQUET-1557 Replace deprecated Avro methods

### PR DESCRIPTION
**Pull request by Fokko**
Some fields are deprecated in Avro 1.8.2 and are being removed in Avro 1.9.0, therefore we want to replace these fields.

https://issues.apache.org/jira/browse/PARQUET-1557

### CODE REVIEW

**Comment by Fokko** [comment]
Gente ping @zivanfi :-)

**Comment by zivanfi** [comment]
> Gentle ping @zivanfi :-)

The reason for me not replying earlier is that... I haven't been asked to review this PR before. :)

**Comment by Fokko** [comment]
Thanks @zivanfi 

As I see you occasionally merging PR's, so I suspect that you would go down the list once a while :-)

**Comment by zivanfi** [comment]
> As I see you occasionally merging PR's, so I suspect that you would go down the list once a while :-)

Recently not so much, only if I am specifically asked to review a change and have time at hand and expertise to do so.

**Pull request merged**
