### PR TITLE
PARQUET-2459: parquet-hadoop tests to work with hadoop 3.4.0

### PR DESCRIPTION
**Pull request by steveloughran**
Removes all log dependencies from hadoop-common, so test runs
do not get confused.

Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references
  them in the PR title. For example, "PARQUET-1234: My Parquet PR"
    - https://issues.apache.org/jira/browse/PARQUET-2459
    - In case you are adding a dependency, check if the license complies with
      the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: it's dependency tuning to fix test runs with -Dhadoop.version=3.4.0

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines
  from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    1. Subject is limited to 50 characters (not including Jira issue reference)
    1. Subject does not end with a period
    1. Subject uses the imperative mood ("add", not "adding")
    1. Body wraps at 72 characters
    1. Body explains "what" and "why", not "how"

### Style
- [X] My contribution adheres to the code style guidelines and Spotless passes.
    - To apply the necessary changes, run `mvn spotless:apply -Pvector-plugins`

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by steveloughran** [comment]
Full dependency list now
```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the MultiThreadedBuilder implementation with a thread count of 10
[INFO] 
[INFO] -----------------< org.apache.parquet:parquet-hadoop >------------------
[INFO] Building Apache Parquet Hadoop 1.14.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.6.1:tree (default-cli) @ parquet-hadoop ---
[INFO] org.apache.parquet:parquet-hadoop:jar:1.14.0-SNAPSHOT
[INFO] +- org.apache.parquet:parquet-column:jar:1.14.0-SNAPSHOT:compile
[INFO] |  +- (org.apache.parquet:parquet-common:jar:1.14.0-SNAPSHOT:compile - omitted for duplicate)
[INFO] |  +- org.apache.parquet:parquet-encoding:jar:1.14.0-SNAPSHOT:compile (scope not updated to compile)
[INFO] |  |  +- (org.apache.parquet:parquet-common:jar:1.14.0-SNAPSHOT:compile - omitted for duplicate)
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.33:compile - omitted for duplicate)
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.33:compile - omitted for duplicate)
[INFO] +- org.apache.parquet:parquet-format-structures:jar:1.14.0-SNAPSHOT:compile
[INFO] |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] +- org.apache.parquet:parquet-common:jar:1.14.0-SNAPSHOT:compile
[INFO] |  +- (org.apache.parquet:parquet-format-structures:jar:1.14.0-SNAPSHOT:compile - omitted for duplicate)
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.33:compile - omitted for duplicate)
[INFO] +- org.apache.parquet:parquet-column:test-jar:tests:1.14.0-SNAPSHOT:test
[INFO] |  +- (org.apache.parquet:parquet-common:jar:1.14.0-SNAPSHOT:test - omitted for duplicate)
[INFO] |  +- (org.apache.parquet:parquet-encoding:jar:1.14.0-SNAPSHOT:test - omitted for duplicate)
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.33:test - omitted for duplicate)
[INFO] +- org.apache.hadoop:hadoop-client:jar:3.3.6:provided
[INFO] |  +- (org.apache.hadoop:hadoop-common:jar:3.3.6:provided - version managed from 3.3.6; omitted for duplicate)
[INFO] |  +- org.apache.hadoop:hadoop-hdfs-client:jar:3.3.6:provided
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1:provided - omitted for conflict with 2.17.0)
[INFO] |  +- org.apache.hadoop:hadoop-yarn-api:jar:3.3.6:provided
[INFO] |  |  +- (org.apache.hadoop.thirdparty:hadoop-shaded-guava:jar:1.1.1:provided - omitted for duplicate)
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.2.11:provided
[INFO] |  |  +- (com.google.protobuf:protobuf-java:jar:2.5.0:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.hadoop.thirdparty:hadoop-shaded-protobuf_3_7:jar:1.1.1:provided - omitted for duplicate)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  +- org.apache.hadoop:hadoop-yarn-client:jar:3.3.6:provided
[INFO] |  |  +- (org.apache.hadoop.thirdparty:hadoop-shaded-guava:jar:1.1.1:provided - omitted for duplicate)
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.51.v20230217:provided
[INFO] |  |  |  +- org.eclipse.jetty:jetty-client:jar:9.4.51.v20230217:provided
[INFO] |  |  |  |  +- (org.eclipse.jetty:jetty-http:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  |  |  \- (org.eclipse.jetty:jetty-io:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  |  +- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  |  +- (org.eclipse.jetty:jetty-io:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  |  \- org.eclipse.jetty.websocket:websocket-common:jar:9.4.51.v20230217:provided
[INFO] |  |  |     +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.51.v20230217:provided
[INFO] |  |  |     +- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  |     \- (org.eclipse.jetty:jetty-io:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  +- (org.apache.hadoop:hadoop-mapreduce-client-core:jar:3.3.6:provided - version managed from 3.3.6; omitted for duplicate)
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:3.3.6:provided
[INFO] |  |  +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:3.3.6:provided
[INFO] |  |  |  +- (org.apache.hadoop:hadoop-yarn-common:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  |  |  +- (org.apache.hadoop:hadoop-yarn-client:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  |  |  +- (org.apache.hadoop:hadoop-mapreduce-client-core:jar:3.3.6:provided - version managed from 3.3.6; omitted for duplicate)
[INFO] |  |  |  \- (com.google.protobuf:protobuf-java:jar:2.5.0:provided - omitted for duplicate)
[INFO] |  |  \- (com.google.protobuf:protobuf-java:jar:2.5.0:provided - omitted for duplicate)
[INFO] |  \- (org.apache.hadoop:hadoop-annotations:jar:3.3.6:provided - omitted for duplicate)
[INFO] +- org.apache.hadoop:hadoop-common:jar:3.3.6:provided (scope not updated to provided)
[INFO] |  +- org.apache.hadoop.thirdparty:hadoop-shaded-protobuf_3_7:jar:1.1.1:provided
[INFO] |  +- (org.apache.hadoop:hadoop-annotations:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  +- org.apache.hadoop.thirdparty:hadoop-shaded-guava:jar:1.1.1:provided
[INFO] |  +- (com.google.guava:guava:jar:27.0-jre:provided - omitted for conflict with 33.1.0-jre)
[INFO] |  +- commons-cli:commons-cli:jar:1.2:provided
[INFO] |  +- org.apache.commons:commons-math3:jar:3.1.1:provided
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:provided
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:provided
[INFO] |  |  +- (commons-logging:commons-logging:jar:1.2:provided - omitted for conflict with 1.1.3)
[INFO] |  |  \- (commons-codec:commons-codec:jar:1.11:provided - omitted for conflict with 1.15)
[INFO] |  +- commons-codec:commons-codec:jar:1.15:provided
[INFO] |  +- (commons-io:commons-io:jar:2.8.0:provided - omitted for conflict with 2.16.1)
[INFO] |  +- commons-net:commons-net:jar:3.9.0:provided
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:provided
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:provided
[INFO] |  +- jakarta.activation:jakarta.activation-api:jar:1.2.1:provided
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:9.4.51.v20230217:provided
[INFO] |  |  +- (javax.servlet:javax.servlet-api:jar:3.1.0:provided - omitted for duplicate)
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.51.v20230217:provided
[INFO] |  |  |  +- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  |  \- (org.eclipse.jetty:jetty-io:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.51.v20230217:provided
[INFO] |  |     \- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  +- org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided
[INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.51.v20230217:provided
[INFO] |  |  +- org.eclipse.jetty:jetty-security:jar:9.4.51.v20230217:provided
[INFO] |  |  |  \- (org.eclipse.jetty:jetty-server:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.51.v20230217:provided
[INFO] |  |     \- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.51.v20230217:provided
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.4.51.v20230217:provided
[INFO] |  |  |  \- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  \- (org.eclipse.jetty:jetty-servlet:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  +- javax.servlet.jsp:jsp-api:jar:2.1:provided
[INFO] |  +- com.sun.jersey:jersey-core:jar:1.19.4:provided
[INFO] |  |  \- javax.ws.rs:jsr311-api:jar:1.1.1:provided
[INFO] |  +- com.sun.jersey:jersey-servlet:jar:1.19.4:provided
[INFO] |  |  \- (com.sun.jersey:jersey-server:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  +- com.github.pjfanning:jersey-json:jar:1.20:provided
[INFO] |  |  +- org.codehaus.jettison:jettison:jar:1.1:provided
[INFO] |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:provided
[INFO] |  |  |  \- (javax.xml.bind:jaxb-api:jar:2.2.2:provided - omitted for conflict with 2.2.11)
[INFO] |  |  \- (com.sun.jersey:jersey-core:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  +- com.sun.jersey:jersey-server:jar:1.19.4:provided
[INFO] |  |  \- (com.sun.jersey:jersey-core:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:provided
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:provided
[INFO] |  |  +- (commons-logging:commons-logging:jar:1.2:provided - omitted for conflict with 1.1.3)
[INFO] |  |  \- (commons-collections:commons-collections:jar:3.2.2:provided - omitted for duplicate)
[INFO] |  +- org.apache.commons:commons-configuration2:jar:2.8.0:provided
[INFO] |  |  +- (org.apache.commons:commons-text:jar:1.9:provided - omitted for conflict with 1.10.0)
[INFO] |  |  \- (commons-logging:commons-logging:jar:1.2:provided - omitted for conflict with 1.1.3)
[INFO] |  +- (org.apache.commons:commons-lang3:jar:3.12.0:provided - omitted for conflict with 3.14.0)
[INFO] |  +- org.apache.commons:commons-text:jar:1.10.0:provided
[INFO] |  |  \- (org.apache.commons:commons-lang3:jar:3.12.0:provided - omitted for conflict with 3.14.0)
[INFO] |  +- org.apache.avro:avro:jar:1.7.7:provided
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:provided
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:provided
[INFO] |  |  |  \- (org.codehaus.jackson:jackson-core-asl:jar:1.9.13:provided - omitted for duplicate)
[INFO] |  |  +- com.thoughtworks.paranamer:paranamer:jar:2.3:provided
[INFO] |  |  +- (org.xerial.snappy:snappy-java:jar:1.0.5:provided - omitted for conflict with 1.1.10.5)
[INFO] |  |  \- (org.apache.commons:commons-compress:jar:1.4.1:provided - omitted for conflict with 1.21)
[INFO] |  +- com.google.re2j:re2j:jar:1.1:provided
[INFO] |  +- com.google.protobuf:protobuf-java:jar:2.5.0:provided
[INFO] |  +- com.google.code.gson:gson:jar:2.9.0:provided
[INFO] |  +- org.apache.hadoop:hadoop-auth:jar:3.3.6:provided
[INFO] |  |  +- (commons-codec:commons-codec:jar:1.15:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.httpcomponents:httpclient:jar:4.5.13:provided - omitted for duplicate)
[INFO] |  |  +- com.nimbusds:nimbus-jose-jwt:jar:9.8.1:provided
[INFO] |  |  |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:provided
[INFO] |  |  +- (org.apache.zookeeper:zookeeper:jar:3.6.3:provided - omitted for duplicate)
[INFO] |  |  +- (io.dropwizard.metrics:metrics-core:jar:3.2.4:provided - omitted for duplicate)
[INFO] |  |  +- org.apache.curator:curator-framework:jar:5.2.0:provided
[INFO] |  |  |  \- (org.apache.curator:curator-client:jar:5.2.0:provided - omitted for duplicate)
[INFO] |  |  +- org.apache.kerby:kerb-simplekdc:jar:1.0.1:provided
[INFO] |  |  |  +- org.apache.kerby:kerb-client:jar:1.0.1:provided
[INFO] |  |  |  |  +- org.apache.kerby:kerby-config:jar:1.0.1:provided
[INFO] |  |  |  |  +- (org.apache.kerby:kerb-core:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  +- org.apache.kerby:kerb-common:jar:1.0.1:provided
[INFO] |  |  |  |  |  +- (org.apache.kerby:kerby-config:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  |  +- org.apache.kerby:kerb-crypto:jar:1.0.1:provided
[INFO] |  |  |  |  |  |  +- (org.apache.kerby:kerby-util:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  |  |  \- (org.apache.kerby:kerb-core:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  |  \- (commons-io:commons-io:jar:2.5:provided - omitted for conflict with 2.16.1)
[INFO] |  |  |  |  +- org.apache.kerby:kerb-util:jar:1.0.1:provided
[INFO] |  |  |  |  |  +- (org.apache.kerby:kerby-config:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  |  +- (org.apache.kerby:kerb-core:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  |  \- (org.apache.kerby:kerb-crypto:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |  \- org.apache.kerby:token-provider:jar:1.0.1:provided
[INFO] |  |  |  |     +- (org.apache.kerby:kerb-core:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |  |     \- (com.nimbusds:nimbus-jose-jwt:jar:3.10:provided - omitted for conflict with 9.8.1)
[INFO] |  |  |  \- org.apache.kerby:kerb-admin:jar:1.0.1:provided
[INFO] |  |  |     +- org.apache.kerby:kerb-server:jar:1.0.1:provided
[INFO] |  |  |     |  +- (org.apache.kerby:kerb-common:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |     |  \- org.apache.kerby:kerb-identity:jar:1.0.1:provided
[INFO] |  |  |     |     +- (org.apache.kerby:kerby-config:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |     |     \- (org.apache.kerby:kerb-core:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |     +- (org.apache.kerby:kerb-util:jar:1.0.1:provided - omitted for duplicate)
[INFO] |  |  |     \- org.apache.kerby:kerby-xdr:jar:1.0.1:provided
[INFO] |  |  \- (org.apache.hadoop.thirdparty:hadoop-shaded-guava:jar:1.1.1:provided - omitted for duplicate)
[INFO] |  +- com.jcraft:jsch:jar:0.1.55:provided
[INFO] |  +- org.apache.curator:curator-client:jar:5.2.0:provided
[INFO] |  +- org.apache.curator:curator-recipes:jar:5.2.0:provided
[INFO] |  |  \- (org.apache.curator:curator-framework:jar:5.2.0:provided - omitted for duplicate)
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:provided
[INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.6.3:provided
[INFO] |  |  +- org.apache.zookeeper:zookeeper-jute:jar:3.6.3:provided
[INFO] |  |  |  \- (org.apache.yetus:audience-annotations:jar:0.5.0:provided - omitted for duplicate)
[INFO] |  |  +- org.apache.yetus:audience-annotations:jar:0.5.0:provided
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.63.Final:provided
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.63.Final:provided
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.63.Final:provided
[INFO] |  |  |  |  \- (io.netty:netty-common:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.63.Final:provided
[INFO] |  |  |  |  \- (io.netty:netty-common:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.63.Final:provided
[INFO] |  |  |  |  +- (io.netty:netty-common:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  |  +- (io.netty:netty-buffer:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  |  \- (io.netty:netty-resolver:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.63.Final:provided
[INFO] |  |  |     +- (io.netty:netty-common:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |     +- (io.netty:netty-buffer:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |     \- (io.netty:netty-transport:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:4.1.63.Final:provided
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.63.Final:provided
[INFO] |  |  |     +- (io.netty:netty-common:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |     +- (io.netty:netty-buffer:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  |     \- (io.netty:netty-transport:jar:4.1.63.Final:provided - omitted for duplicate)
[INFO] |  |  \- log4j:log4j:jar:1.2.17:provided
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:3.2.4:provided
[INFO] |  +- org.apache.commons:commons-compress:jar:1.21:provided
[INFO] |  +- org.apache.kerby:kerb-core:jar:1.0.1:provided
[INFO] |  |  \- org.apache.kerby:kerby-pkix:jar:1.0.1:provided
[INFO] |  |     +- org.apache.kerby:kerby-asn1:jar:1.0.1:provided
[INFO] |  |     \- org.apache.kerby:kerby-util:jar:1.0.1:provided
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1:provided - omitted for conflict with 2.17.0)
[INFO] |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:provided
[INFO] |  +- com.fasterxml.woodstox:woodstox-core:jar:5.4.0:provided
[INFO] |  |  \- (org.codehaus.woodstox:stax2-api:jar:4.2:provided - omitted for conflict with 4.2.1)
[INFO] |  +- dnsjava:dnsjava:jar:2.1.7:provided
[INFO] |  \- (org.xerial.snappy:snappy-java:jar:1.1.8.2:provided - omitted for conflict with 1.1.10.5)
[INFO] +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:3.3.6:provided (scope not updated to provided)
[INFO] |  +- (org.apache.hadoop:hadoop-yarn-client:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  +- org.apache.hadoop:hadoop-yarn-common:jar:3.3.6:provided
[INFO] |  |  +- (org.apache.hadoop:hadoop-hdfs-client:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.hadoop:hadoop-yarn-api:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.hadoop:hadoop-auth:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  |  +- (javax.xml.bind:jaxb-api:jar:2.2.11:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.commons:commons-compress:jar:1.21:provided - omitted for duplicate)
[INFO] |  |  +- (javax.servlet:javax.servlet-api:jar:3.1.0:provided - omitted for duplicate)
[INFO] |  |  +- (commons-codec:commons-codec:jar:1.15:provided - omitted for duplicate)
[INFO] |  |  +- (org.eclipse.jetty:jetty-util:jar:9.4.51.v20230217:provided - omitted for duplicate)
[INFO] |  |  +- (com.sun.jersey:jersey-core:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  |  +- com.sun.jersey:jersey-client:jar:1.19.4:provided
[INFO] |  |  |  \- (com.sun.jersey:jersey-core:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.hadoop.thirdparty:hadoop-shaded-guava:jar:1.1.1:provided - omitted for duplicate)
[INFO] |  |  +- (commons-cli:commons-cli:jar:1.2:provided - omitted for duplicate)
[INFO] |  |  +- (org.apache.hadoop:hadoop-annotations:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  |  +- (com.google.inject.extensions:guice-servlet:jar:4.0:provided - omitted for duplicate)
[INFO] |  |  +- (com.google.protobuf:protobuf-java:jar:2.5.0:provided - omitted for duplicate)
[INFO] |  |  +- (commons-io:commons-io:jar:2.8.0:provided - omitted for conflict with 2.16.1)
[INFO] |  |  +- com.google.inject:guice:jar:4.0:provided
[INFO] |  |  |  +- javax.inject:javax.inject:jar:1:provided
[INFO] |  |  |  +- aopalliance:aopalliance:jar:1.0:provided
[INFO] |  |  |  \- (com.google.guava:guava:jar:16.0.1:provided - omitted for conflict with 33.1.0-jre)
[INFO] |  |  +- (com.sun.jersey:jersey-server:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  |  +- (com.github.pjfanning:jersey-json:jar:1.20:provided - omitted for duplicate)
[INFO] |  |  +- com.sun.jersey.contribs:jersey-guice:jar:1.19.4:provided
[INFO] |  |  |  +- (javax.inject:javax.inject:jar:1:provided - omitted for duplicate)
[INFO] |  |  |  +- (com.google.inject:guice:jar:3.0:provided - omitted for conflict with 4.0)
[INFO] |  |  |  +- (com.google.inject.extensions:guice-servlet:jar:3.0:provided - omitted for conflict with 4.0)
[INFO] |  |  |  \- (com.sun.jersey:jersey-servlet:jar:1.19.4:provided - omitted for duplicate)
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1:provided - omitted for conflict with 2.17.0)
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.7:provided
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:provided
[INFO] |  |  |  |  \- (jakarta.activation:jakarta.activation-api:jar:1.2.1:provided - omitted for duplicate)
[INFO] |  |  |  \- (jakarta.activation:jakarta.activation-api:jar:1.2.1:provided - omitted for duplicate)
[INFO] |  |  \- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.12.7:provided
[INFO] |  |     +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.12.7:provided
[INFO] |  |     |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |     |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.7:provided - omitted for conflict with 2.17.0)
[INFO] |  |     \- (com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.7:provided - omitted for duplicate)
[INFO] |  +- (org.apache.hadoop:hadoop-hdfs-client:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.7.1:provided - omitted for conflict with 2.17.0)
[INFO] |  +- (com.google.protobuf:protobuf-java:jar:2.5.0:provided - omitted for duplicate)
[INFO] |  +- (org.apache.avro:avro:jar:1.7.7:provided - omitted for duplicate)
[INFO] |  +- (org.apache.hadoop:hadoop-annotations:jar:3.3.6:provided - omitted for duplicate)
[INFO] |  +- com.google.inject.extensions:guice-servlet:jar:4.0:provided
[INFO] |  |  \- (com.google.inject:guice:jar:4.0:provided - omitted for duplicate)
[INFO] |  \- io.netty:netty:jar:3.10.6.Final:provided
[INFO] +- org.apache.hadoop:hadoop-annotations:jar:3.3.6:provided (scope not updated to provided)
[INFO] |  \- jdk.tools:jdk.tools:jar:1.8:system
[INFO] +- org.apache.parquet:parquet-jackson:jar:1.14.0-SNAPSHOT:runtime
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.17.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.0:compile
[INFO] |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.17.0:compile - omitted for duplicate)
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.14.9:compile
[INFO] +- org.xerial.snappy:snappy-java:jar:1.1.10.5:compile
[INFO] +- io.airlift:aircompressor:jar:0.26:compile
[INFO] +- commons-pool:commons-pool:jar:1.6:compile
[INFO] +- it.unimi.dsi:fastutil:jar:8.5.13:compile
[INFO] +- com.github.luben:zstd-jni:jar:1.5.5-11:compile
[INFO] +- com.google.guava:guava:jar:33.1.0-jre:test (scope not updated to provided)
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.2:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:test - omitted for duplicate)
[INFO] |  +- org.checkerframework:checker-qual:jar:3.42.0:test
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.26.1:test
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:3.0.0:test
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.33:test
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.33:test - omitted for duplicate)
[INFO] +- com.squareup.okhttp3:okhttp:jar:4.12.0:test
[INFO] |  +- com.squareup.okio:okio:jar:3.6.0:test
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.6.0:test
[INFO] |  |     +- (org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.10:test - omitted for conflict with 1.8.21)
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.10:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.8.21:test
[INFO] |     +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.8.21:test
[INFO] |     |  +- (org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.8.21:test - omitted for conflict with 1.9.10)
[INFO] |     |  \- org.jetbrains:annotations:jar:13.0:test
[INFO] |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.8.21:test
[INFO] |        \- (org.jetbrains.kotlin:kotlin-stdlib:jar:1.8.21:test - omitted for duplicate)
[INFO] +- org.slf4j:slf4j-api:jar:1.7.33:compile
[INFO] +- commons-io:commons-io:jar:2.16.1:test (scope not updated to provided)
[INFO] +- net.openhft:zero-allocation-hashing:jar:0.16:test
[INFO] +- org.apache.commons:commons-lang3:jar:3.14.0:test (scope not updated to provided)
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.easymock:easymock:jar:5.2.0:test
[INFO]    \- org.objenesis:objenesis:jar:3.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.175 s (Wall Clock)
[INFO] Finished at: 2024-04-17T16:26:15+01:00
[INFO] ------------------------------------------------------------------------
```

**Review by Fokko — APPROVED** [review]
LGTM, Thanks for cleaning this up @steveloughran

**Review by wgtmac — APPROVED** [review]

**Comment by Fokko** [comment]
@steveloughran Wanted others also give some time to review this.

> note: there is something odd with maven here, we will have to see if we can fix for 3.4.1, though we did try for 3.4.0 already and clearly didn't take...

Looks like you're referring to [HADOOP-19153](https://issues.apache.org/jira/browse/HADOOP-19153), would be good to get that fixed indeed :)

**Comment by steveloughran** [comment]
> Looks like you're referring to [HADOOP-19153](https://issues.apache.org/jira/browse/HADOOP-19153), would be good to get that fixed indeed :)

yeah. here's the thing: we do exclude it! and it doesn't get into hadoop-* tests. but when we export hadoop-client it creeps back in.

I have no idea what is going on here

**Comment by steveloughran** [comment]
update: yeah, found the problem. will be fixed in 3.4.1

no harm in having this pr in everywhere though and it ensures 3.4.0 builds work

**Pull request merged**
