### PR TITLE
PARQUET-336: Fix ArrayIndexOutOfBounds in checkDeltaByteArrayProblem

### PR DESCRIPTION
**Pull request by isnotinvain**

### CODE REVIEW

**Comment by rdblue** [comment]
@isnotinvain, I think you're right on this one and the fix looks good.

Is it easy to add a test for this case? It seems like we should have something that catches problems like this when all of the row groups are filtered out for a task.

**Comment by isnotinvain** [comment]
Yeah, I am not sure how easy this is to test w/o introducing a mini-cluster test (which can be pretty painful to setup)

I can try and see if a narrow unit-test is do-able.

**Comment by isnotinvain** [comment]
Actually, wasn't hard to add a test that hits the issue, seems this issue is hit in local mode as well.

**Comment by tsdeng** [comment]
+1

**Pull request closed without merging**
