### PR TITLE
PARQUET-253: Fixes Javadoc of AvroSchemaConverter

### PR DESCRIPTION
**Pull request by liancheng**
Got confused by the original Javadoc at first and didn't realize `AvroSchemaConverter` is also capable to convert a Parquet schema to an Avro schema.

[Review on Reviewable](https://reviewable.io/reviews/apache/incubator-parquet-mr/173)

### CODE REVIEW

**Comment by rdblue** [comment]
@liancheng could you open an issue for this and update the PR title? We use the Spark script and only merge PRs with a JIRA ID in the title: "PARQUET-XYZ: Fixes Javadoc..."

Thanks!

**Comment by liancheng** [comment]
@rdblue Done. Didn't realize Parquet is more strict than Spark, JIRA ticket is optional there when merging minor PRs :)

**Comment by rdblue** [comment]
Thanks for fixing that! Unfortunately because of the org.apache rename, I can't merge this unless you rebase. Thanks!

**Comment by rdblue** [comment]
@liancheng could you rebase this? It isn't passing the merge script.

**Comment by rdblue** [comment]
Nevermind. It looks like the script was lying and I could merge it. It just had to resort to a 3-way merge.

**Pull request closed without merging**
