### PR TITLE
PARQUET-196: parquet-tools command for row count & size

### PR DESCRIPTION
**Pull request by swapnilushinde**
This is a rebase on already existing PR-
https://github.com/apache/parquet-mr/pull/132

### CODE REVIEW

**Comment by swapnilushinde** [comment]
Thank you @julienledem.

**Comment by swapnilushinde** [comment]
@julienledem I fixed spacing. Please check and merge if looks good.

**Comment by julienledem** [comment]
please update the title to start with "PARQUET-196: ..." (uppercase) to please the merge tool

**Comment by swapnilushinde** [comment]
@julienledem Done

**Pull request closed without merging**
