### PR TITLE
PARQUET-765 - Upgrade Avro to 1.8.1

### PR DESCRIPTION
**Pull request by gszadovszky**
Escaping the field name `date` to make the test compatible to Avro 1.8.1 as _date_ is a keyword in avdl from 1.8.1.

Tested by setting the maven parameter `avro.version` to `1.8.1` and initiated a full build by `mvn clean install`.

### CODE REVIEW

**Comment by julienledem** [comment]
LGTM.
How do we decide what version of avro we want in the pom?
should we set the version to 1.8.1?

**Comment by gszadovszky** [comment]
I don't know if this issue was stopped us using 1.8.1 or just forgot to upgrade to the latest one. 
As this is a minor release upgrade I would don't see any reason why we cannot set it to 1.8.1.
Do you agree on increasing the avro version in this commit?

**Comment by julienledem** [comment]
sounds good to me

**Comment by gszadovszky** [comment]
Changed the avro version to 1.8.1. Modified the title of the JIRA.

**Pull request closed without merging**
