### PR TITLE
PARQUET-2274: Remove Yetus

### PR DESCRIPTION
**Pull request by Fokko**
I don't think this is used anywhere anymore.

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"
  - https://issues.apache.org/jira/browse/PARQUET-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by wgtmac — APPROVED** [review]
LGTM though I am not familiar with this tool.

cc @gszadovszky

**Comment by shangxinli** [comment]
Yeah, adding some comments could help although sometimes people ignore it. But some of them are already used by other tool  like the columnIndex one.

**Comment by shangxinli** [comment]
@Fokko Do you think you can add some comment and we merge this PR in?

**Comment by Fokko** [comment]
@shangxinli Sorry for the long wait, I've added the comments 👍

**Comment by wgtmac** [comment]
@sekikn Do you have any comment?

**Comment by sekikn** [comment]
No, I agree with replacing audience annotations with appropriate comments for now, since we don't have a tool for enforcing restriction based on the annotations, as mentioned by @gszadovszky.

**Comment by Fokko** [comment]
Thank you @sekikn for confirming. I'll move this forward.

**Pull request merged**
